---
environment: "development"
redis:
  username:
  password:
  server: "0.0.0.0:16379"
  database: "0"
  pool: "30"
  process: "1"
plugins:
  codeamp:
    workers: 1
    postgres:
      host: "0.0.0.0"
      port: "15432"
      user: "postgres"
      dbname: "codeamp"
      sslmode: "disable"
      password: ""
    service_address: ":3011"
    websockets:
      path: "/ws"
  websockets:
    workers: 1
    service_address: ":3013"
  git_sync:
    workers: 1
    workdir: "/tmp/git_sync" 
  heartbeat:
    workers: 1
